### ISSUE TITLE
Breakage with glue 1.8.0

### ISSUE THREAD

**Issue by jennybc** [r-world-devs/shinyCohortBuilder#61]
I just released glue 1.8.0 (https://github.com/tidyverse/glue/issues/341) and there is breakage of shinyCohortBuilder. I detected this in December 2023 and at the time shinyCohortBuilder did not appear to be on GitHub? I.e. DESCRIPTION did not contain a link to this repo. So I sent an email to the maintainer krystian8207@gmail.com on Dec 21, 2023 with subject "shinyCohortBuilder check failure with dev glue".

I see that shinyCohortBuilder recently updated on CRAN and now provides its GitHub repo. Here's the sort of issue I opened for other affected revdeps (and this is essentially the content of the December 2023 email):

This issue is inspired by doing revdep checks for glue. ~In the next release of glue, which is _very soon_~ (release has now happened), `glue::glue()` will error when `.envir` is not an actual environment. `.envir` has always been documented to be an environment and I've been working to make this actually true.

`glue_data()` *does* officially accept something "list-ish" as `.x`. So you should switch to `glue_data(.x = list_ish_thing, ...)` as opposed to `glue(.envir = list_ish_thing, ...)` in many places here in this package.

Relevant links in glue:

https://github.com/tidyverse/glue/issues/308
https://github.com/tidyverse/glue/commit/e2b74ff17704261b5a7da25b4ebd2dec94740764
https://github.com/tidyverse/glue/issues/341

Here's what the most recent revdep checks for glue show for shinyCohortBuilder:
https://github.com/tidyverse/glue/blob/main/revdep/problems.md#shinyCohortBuilder

**Comment by galachad** [comment]
Thank you @jennybc for creating the issue, we will resubmit hot fix to cran next week.
